
weather_icons = {
    "clear sky": "☀️",
    "few clouds": "⛅",
    "scattered clouds": "🌥️",
    "broken clouds": "☁️",
    "overcast clouds": "🌥️",
    "mist": "🌫️",
    "haze": "🌫️",
    "smoke": "🌫️",
    "fog": "🌫️",
    "light intensity drizzle": "🌧️",
    "drizzle": "🌧️",
    "heavy intensity drizzle": "🌧️",
    "light intensity drizzle rain": "🌧️",
    "drizzle rain": "🌧️",
    "heavy intensity drizzle rain": "🌧️",
    "shower rain and drizzle": "🌧️",
    "heavy shower rain and drizzle": "🌧️",
    "shower drizzle": "🌧️",
    "light rain": "🌧️",
    "moderate rain": "🌧️",
    "heavy intensity rain": "🌧️",
    "very heavy rain": "🌧️",
    "extreme rain": "🌧️",
    "freezing rain": "❄️🌧️",
    "light intensity shower rain": "🌧️",
    "shower rain": "🌧️",
    "heavy intensity shower rain": "🌧️",
    "ragged shower rain": "🌧️",
    "light snow": "❄️🌨️",
    "snow": "❄️🌨️",
    "heavy snow": "❄️🌨️",
    "sleet": "❄️🌨️",
    "shower sleet": "❄️🌨️",
    "light rain and snow": "❄️🌨️",
    "rain and snow": "❄️🌨️",
    "light shower snow": "❄️🌨️",
    "shower snow": "❄️🌨️",
    "heavy shower snow": "❄️🌨️",
    "mist": "🌫️",
    "smoke": "🌫️",
    "haze": "🌫️",
    "sand/ dust whirls": "🌀",
    "fog": "🌫️",
    "sand": "🌫️",
    "dust": "🌫️",
    "volcanic ash": "🌋",
    "squalls": "🌬️",
    "tornado": "🌪️",
    "clear sky": "☀️",
    "light rain": "🌦️",
    "thunderstorm with rain": "⛈️🌧️",
    "thunderstorm with heavy rain": "⛈️🌧️",
    "thunderstorm with light drizzle": "⛈️🌧️",
    "thunderstorm with drizzle": "⛈️🌧️",
    "thunderstorm with heavy drizzle": "⛈️🌧️",
    "thunderstorm with hail": "⛈️🌨️",
    "thunderstorm with heavy hail": "⛈️🌨️",
    "thunderstorm with light rain": "⛈️🌦️",
    "thunderstorm with rain": "⛈️🌦️",
    "thunderstorm with heavy rain": "⛈️🌦️",
    "thunderstorm with light drizzle": "⛈️🌦️",
    "thunderstorm with drizzle": "⛈️🌦️",
    "thunderstorm with heavy drizzle": "⛈️🌦️",
    "thunderstorm with hail": "⛈️🌦️",
    "thunderstorm with heavy hail": "⛈️🌦️",
    "clear sky": "☀️",
    "cloudy sky": "☁️",
    "hurricane": "🌀",
    "cold": "❄️",
    "hot": "🔥",
    "windy": "💨",
    "hail": "🌨️",
}


"""

association_to_add = [
        CityFacilityAssociation (city_id = 1, facility_id = 3),
        CityFacilityAssociation (city_id = 1, facility_id = 9),
        CityFacilityAssociation (city_id = 1, facility_id = 10),
        CityFacilityAssociation (city_id = 2, facility_id = 3),
        CityFacilityAssociation (city_id = 2, facility_id = 4),
        CityFacilityAssociation (city_id = 2, facility_id = 6),
        CityFacilityAssociation (city_id = 3, facility_id = 10),
        CityFacilityAssociation (city_id = 3, facility_id = 5),
        CityFacilityAssociation (city_id = 3, facility_id = 2),
        CityFacilityAssociation (city_id = 4, facility_id = 8),
        CityFacilityAssociation (city_id = 4, facility_id = 5),
        CityFacilityAssociation (city_id = 4, facility_id = 10),
        CityFacilityAssociation (city_id = 5, facility_id = 4),
        CityFacilityAssociation (city_id = 5, facility_id = 5),
        CityFacilityAssociation (city_id = 5, facility_id = 6),
        CityFacilityAssociation (city_id = 6, facility_id = 3),
        CityFacilityAssociation (city_id = 6, facility_id = 5),
        CityFacilityAssociation (city_id = 6, facility_id = 6),
        CityFacilityAssociation (city_id = 7, facility_id = 5),
        CityFacilityAssociation (city_id = 7, facility_id = 9),
        CityFacilityAssociation (city_id = 7, facility_id = 4),
        CityFacilityAssociation (city_id = 8, facility_id = 6),
        CityFacilityAssociation (city_id = 8, facility_id = 3),
        CityFacilityAssociation (city_id = 8, facility_id = 9),
        CityFacilityAssociation (city_id = 9, facility_id = 10),
        CityFacilityAssociation (city_id = 9, facility_id = 3),
        CityFacilityAssociation (city_id = 9, facility_id = 5),
        CityFacilityAssociation (city_id = 10, facility_id = 2),
        CityFacilityAssociation (city_id = 10, facility_id = 8),
        CityFacilityAssociation (city_id = 10, facility_id = 5),
        CityFacilityAssociation (city_id = 11, facility_id = 1),
        CityFacilityAssociation (city_id = 11, facility_id = 9),
        CityFacilityAssociation (city_id = 11, facility_id = 6),
        CityFacilityAssociation (city_id = 12, facility_id = 4),
        CityFacilityAssociation (city_id = 12, facility_id = 7),
        CityFacilityAssociation (city_id = 12, facility_id = 2),
        CityFacilityAssociation (city_id = 13, facility_id = 5),
        CityFacilityAssociation (city_id = 13, facility_id = 10),
        CityFacilityAssociation (city_id = 13, facility_id = 8),
        CityFacilityAssociation (city_id = 14, facility_id = 4),
        CityFacilityAssociation (city_id = 14, facility_id = 3),
        CityFacilityAssociation (city_id = 14, facility_id = 2),
        CityFacilityAssociation (city_id = 15, facility_id = 8),
        CityFacilityAssociation (city_id = 15, facility_id = 4),
        CityFacilityAssociation (city_id = 15, facility_id = 6),
        CityFacilityAssociation (city_id = 16, facility_id = 8),
        CityFacilityAssociation (city_id = 16, facility_id = 3),
        CityFacilityAssociation (city_id = 16, facility_id = 6),
        CityFacilityAssociation (city_id = 17, facility_id = 2),
        CityFacilityAssociation (city_id = 17, facility_id = 5),
        CityFacilityAssociation (city_id = 17, facility_id = 1),
        CityFacilityAssociation (city_id = 18, facility_id = 6),
        CityFacilityAssociation (city_id = 18, facility_id = 8),
        CityFacilityAssociation (city_id = 18, facility_id = 7),
        CityFacilityAssociation (city_id = 19, facility_id = 2),
        CityFacilityAssociation (city_id = 19, facility_id = 8),
        CityFacilityAssociation (city_id = 19, facility_id = 4),
        CityFacilityAssociation (city_id = 20, facility_id = 10),
        CityFacilityAssociation (city_id = 20, facility_id = 7),
        CityFacilityAssociation (city_id = 20, facility_id = 6),
        CityFacilityAssociation (city_id = 21, facility_id = 9),
        CityFacilityAssociation (city_id = 21, facility_id = 3),
        CityFacilityAssociation (city_id = 21, facility_id = 4),
        CityFacilityAssociation (city_id = 22, facility_id = 8),
        CityFacilityAssociation (city_id = 22, facility_id = 2),
        CityFacilityAssociation (city_id = 22, facility_id = 9),
        CityFacilityAssociation (city_id = 23, facility_id = 2),
        CityFacilityAssociation (city_id = 23, facility_id = 6),
        CityFacilityAssociation (city_id = 23, facility_id = 10),
        CityFacilityAssociation (city_id = 24, facility_id = 9),
        CityFacilityAssociation (city_id = 24, facility_id = 10),
        CityFacilityAssociation (city_id = 24, facility_id = 3),
        CityFacilityAssociation (city_id = 25, facility_id = 1),
        CityFacilityAssociation (city_id = 25, facility_id = 2),
        CityFacilityAssociation (city_id = 25, facility_id = 8),
        CityFacilityAssociation (city_id = 26, facility_id = 6),
        CityFacilityAssociation (city_id = 26, facility_id = 8),
        CityFacilityAssociation (city_id = 26, facility_id = 10),
        CityFacilityAssociation (city_id = 27, facility_id = 1),
        CityFacilityAssociation (city_id = 27, facility_id = 2),
        CityFacilityAssociation (city_id = 27, facility_id = 7),
        CityFacilityAssociation (city_id = 28, facility_id = 6),
        CityFacilityAssociation (city_id = 28, facility_id = 1),
        CityFacilityAssociation (city_id = 28, facility_id = 8),
        CityFacilityAssociation (city_id = 29, facility_id = 8),
        CityFacilityAssociation (city_id = 29, facility_id = 3),
        CityFacilityAssociation (city_id = 29, facility_id = 2),
        CityFacilityAssociation (city_id = 30, facility_id = 6),
        CityFacilityAssociation (city_id = 30, facility_id = 7),
        CityFacilityAssociation (city_id = 30, facility_id = 10),
        CityFacilityAssociation (city_id = 31, facility_id = 1),
        CityFacilityAssociation (city_id = 31, facility_id = 8),
        CityFacilityAssociation (city_id = 31, facility_id = 2),
        CityFacilityAssociation (city_id = 32, facility_id = 5),
        CityFacilityAssociation (city_id = 32, facility_id = 8),
        CityFacilityAssociation (city_id = 32, facility_id = 1),
        CityFacilityAssociation (city_id = 33, facility_id = 3),
        CityFacilityAssociation (city_id = 33, facility_id = 10),
        CityFacilityAssociation (city_id = 33, facility_id = 6),
        CityFacilityAssociation (city_id = 34, facility_id = 1),
        CityFacilityAssociation (city_id = 34, facility_id = 7),
        CityFacilityAssociation (city_id = 34, facility_id = 2),
        CityFacilityAssociation (city_id = 35, facility_id = 9),
        CityFacilityAssociation (city_id = 35, facility_id = 3),
        CityFacilityAssociation (city_id = 35, facility_id = 1),
        CityFacilityAssociation (city_id = 36, facility_id = 6),
        CityFacilityAssociation (city_id = 36, facility_id = 4),
        CityFacilityAssociation (city_id = 36, facility_id = 5),
        CityFacilityAssociation (city_id = 37, facility_id = 10),
        CityFacilityAssociation (city_id = 37, facility_id = 6),
        CityFacilityAssociation (city_id = 37, facility_id = 3),
        CityFacilityAssociation (city_id = 38, facility_id = 10),
        CityFacilityAssociation (city_id = 38, facility_id = 7),
        CityFacilityAssociation (city_id = 38, facility_id = 2),
        CityFacilityAssociation (city_id = 39, facility_id = 4),
        CityFacilityAssociation (city_id = 39, facility_id = 1),
        CityFacilityAssociation (city_id = 39, facility_id = 5),
        CityFacilityAssociation (city_id = 40, facility_id = 10),
        CityFacilityAssociation (city_id = 40, facility_id = 8),
        CityFacilityAssociation (city_id = 40, facility_id = 6),
        CityFacilityAssociation (city_id = 41, facility_id = 8),
        CityFacilityAssociation (city_id = 41, facility_id = 4),
        CityFacilityAssociation (city_id = 41, facility_id = 9),
        CityFacilityAssociation (city_id = 42, facility_id = 10),
        CityFacilityAssociation (city_id = 42, facility_id = 9),
        CityFacilityAssociation (city_id = 42, facility_id = 3),
        CityFacilityAssociation (city_id = 43, facility_id = 6),
        CityFacilityAssociation (city_id = 43, facility_id = 2),
        CityFacilityAssociation (city_id = 43, facility_id = 8),
        CityFacilityAssociation (city_id = 44, facility_id = 1),
        CityFacilityAssociation (city_id = 44, facility_id = 4),
        CityFacilityAssociation (city_id = 44, facility_id = 5),
        CityFacilityAssociation (city_id = 45, facility_id = 4),
        CityFacilityAssociation (city_id = 45, facility_id = 2),
        CityFacilityAssociation (city_id = 45, facility_id = 3),
        CityFacilityAssociation (city_id = 46, facility_id = 3),
        CityFacilityAssociation (city_id = 46, facility_id = 9),
        CityFacilityAssociation (city_id = 46, facility_id = 4),
        CityFacilityAssociation (city_id = 47, facility_id = 4),
        CityFacilityAssociation (city_id = 47, facility_id = 3),
        CityFacilityAssociation (city_id = 47, facility_id = 10),
        CityFacilityAssociation (city_id = 48, facility_id = 4),
        CityFacilityAssociation (city_id = 48, facility_id = 9),
        CityFacilityAssociation (city_id = 48, facility_id = 7),
        CityFacilityAssociation (city_id = 49, facility_id = 2),
        CityFacilityAssociation (city_id = 49, facility_id = 4),
        CityFacilityAssociation (city_id = 49, facility_id = 1),
        CityFacilityAssociation (city_id = 50, facility_id = 7),
        CityFacilityAssociation (city_id = 50, facility_id = 5),
        CityFacilityAssociation (city_id = 50, facility_id = 2),
]
"""
