"""add FK to classes

Revision ID: 006895a8c21a
Revises: e3fb3d80e214
Create Date: 2023-08-15 17:24:48.042555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006895a8c21a'
down_revision: Union[str, None] = 'e3fb3d80e214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('county_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cities_state', 'States', ['state_id'], ['id'])
        batch_op.create_foreign_key('fk_cities_county', 'Counties', ['county_id'], ['id'])
        batch_op.drop_column('county_name')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_cities_county', type_='foreignkey')
        batch_op.drop_constraint('fk_cities_state', type_='foreignkey')
        batch_op.drop_column('county_id')
        batch_op.drop_column('state_id')
    # ### end Alembic commands ###
