"""states and counties related

Revision ID: c5fcbfbc59f7
Revises: 006895a8c21a
Create Date: 2023-08-22 02:30:59.234060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5fcbfbc59f7'
down_revision: Union[str, None] = '006895a8c21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Counties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_counties_state_id', 'States', ['state_id'], ['id'])


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Counties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_counties_state_id', type_='foreignkey')
        batch_op.drop_column('state_id')

    # ### end Alembic commands ###
